### ISSUE TITLE
Can't update the font

### ISSUE THREAD

**Issue by aminya** [zunderscore/chocolatey-packages#8] opened 2020-09-17 22:51 UTC
![image](https://user-images.githubusercontent.com/16418197/93536374-766dff00-f90e-11ea-832f-3b29380bd8d0.png)
![image](https://user-images.githubusercontent.com/16418197/93536412-8be32900-f90e-11ea-9d4d-ed3becfc5748.png)
![image](https://user-images.githubusercontent.com/16418197/93536468-a7e6ca80-f90e-11ea-9ada-6bd90fb3b6e6.png)

**Comment by zunderscore** [comment] 2020-09-17 22:55
Duplicate of #3

**Closed as completed** 2020-09-17 22:55 UTC
