### ISSUE TITLE
[Cascadia Code] Uninstaller always try to uninstall legacy font

### ISSUE THREAD

**Issue by CookieHCl** [zunderscore/chocolatey-packages#17] opened 2021-08-23 07:10 UTC
![image](https://user-images.githubusercontent.com/28638469/130404719-a8531ba4-3faf-4f11-a26a-5fc7fff1844b.png)

I don't have legacy font(`Cascadia.ttf`), and I only have current font(`CascadiaCode.ttf`).  
However, since uninstaller always try to uninstall legacy font, uninstall always fail with `WARNING: File Path 'C:\Windows\Fonts\Cascadia.ttf' does not exist!` and `Error uninstalling legacy Cascadia Code font`.

Why don't you check existence before uninstalling legacy font?

**Comment by zunderscore** [comment] 2021-08-23 10:41
Because of how font management works via command line, it's not always possible or reliable to check existence before attempting to uninstall. That's why this is a warning and not an error. Closing, as this is by design.

**Closed as completed by zunderscore** 2021-08-23 10:41 UTC

**Comment by CookieHCl** [comment] 2021-08-23 15:03
@zunderscore I didn't know that... But it seems failure during uninstalling legacy font [raises error](https://github.com/zunderscore/chocolatey-packages/blob/main/cascadia/chocolateyuninstall.ps1#L11) instead of warning!

**Comment by zunderscore** [comment] 2021-08-23 20:00
@CookieHCl Yes, that's if the process fails unexpectedly, like when you don't run the **choco** command as an administrator. When running as admin, even if the font file doesn't exist, there should be no error as the **Uninstall-ChocolateyFont** command will simply [skip non-existent files](https://github.com/teknowledgist/Chocolatey-packages/blob/36668569d19486fed4e566a276980011fcce4edd/extensions/chocolatey-font-helpers.extension/extensions/Uninstall-ChocolateyFont.ps1#L65-L70).

I just tested this in my local environment which has never had the legacy font and it had no issues.

![image](https://user-images.githubusercontent.com/1764877/130511482-b128eb45-ded4-405d-8c77-5f7912a0dd99.png)

Keeping this closed.
